sudo: false
language: node_js
before_install:
  - npm config set registry https://:2020-06-04T13%3A01%3A44.432Z@time-machines-npm.sealsecurity.io/
  - npm install npm -g 
    --registry=https://:2020-06-04T13%3A01%3A44.432Z@time-machines-npm.sealsecurity.io/
node_js:
  - "9"
  - '14'
  - "12"
  - "10"
  - "8"
matrix:
    include:
      - node_js: "8"
        env: TEST_SUITE=coverage
      - node_js: "8"
        env: TEST_SUITE=lint
env:
  - TEST_SUITE=test
script: npm run-script $TEST_SUITE
